# Generated by Django 4.2.4 on 2023-08-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=10, unique=True)),
                ('state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=10)),
                ('skills', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='')),
                ('address', models.CharField(max_length=40)),
            ],
        ),
    ]
