# Generated by Django 4.2.4 on 2023-08-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
