# Generated by Django 4.2.4 on 2023-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0002_alter_employee_detail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='address',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='city',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='experience',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='skills',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='employee_detail',
            name='state',
            field=models.CharField(max_length=70),
        ),
    ]
