# Generated by Django 4.2.4 on 2023-08-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detail', '0004_remove_employee_detail_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_detail',
            name='skills',
            field=models.CharField(max_length=70),
        ),
    ]
